"""Initial migration

Revision ID: 157f94e7872b
Revises: 
Create Date: 2024-11-11 22:04:11.442966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '157f94e7872b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('tiempo_optimista_total', sa.Float(), nullable=True),
    sa.Column('tiempo_pesimista_total', sa.Float(), nullable=True),
    sa.Column('tiempo_esperado_total', sa.Float(), nullable=True),
    sa.Column('desviacion_estandar_total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_id'), 'proyectos', ['id'], unique=False)
    op.create_index(op.f('ix_proyectos_nombre'), 'proyectos', ['nombre'], unique=False)
    op.create_table('hitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tiempo_optimista', sa.Float(), nullable=True),
    sa.Column('tiempo_pesimista', sa.Float(), nullable=True),
    sa.Column('tiempo_esperado', sa.Float(), nullable=True),
    sa.Column('varianza', sa.Float(), nullable=True),
    sa.Column('desviacion_estandar', sa.Float(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hitos_id'), 'hitos', ['id'], unique=False)
    op.create_index(op.f('ix_hitos_nombre'), 'hitos', ['nombre'], unique=False)
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('hito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hito_id'], ['hitos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_id'), 'tareas', ['id'], unique=False)
    op.create_index(op.f('ix_tareas_nombre'), 'tareas', ['nombre'], unique=False)
    op.create_table('subtareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tiempo_probable', sa.Float(), nullable=False),
    sa.Column('tiempo_optimista', sa.Float(), nullable=False),
    sa.Column('tiempo_pesimista', sa.Float(), nullable=False),
    sa.Column('tiempo_esperado', sa.Float(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=True),
    sa.Column('dependencia_id', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('subtarea_id_csv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtareas_id'), 'subtareas', ['id'], unique=False)
    op.create_index(op.f('ix_subtareas_nombre'), 'subtareas', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtareas_nombre'), table_name='subtareas')
    op.drop_index(op.f('ix_subtareas_id'), table_name='subtareas')
    op.drop_table('subtareas')
    op.drop_index(op.f('ix_tareas_nombre'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_id'), table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_hitos_nombre'), table_name='hitos')
    op.drop_index(op.f('ix_hitos_id'), table_name='hitos')
    op.drop_table('hitos')
    op.drop_index(op.f('ix_proyectos_nombre'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_id'), table_name='proyectos')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
