"""initial migration

Revision ID: 78b9d8b0f210
Revises: 
Create Date: 2024-11-12 10:15:39.422890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78b9d8b0f210'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('PERT', sa.Float(), nullable=False),
    sa.Column('tiempo_optimista', sa.Float(), nullable=False),
    sa.Column('tiempo_pesimista', sa.Float(), nullable=False),
    sa.Column('tiempo_probable', sa.Float(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=True),
    sa.Column('dependencia_id', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('subtarea_id_csv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtareas_id'), 'subtareas', ['id'], unique=False)
    op.create_index(op.f('ix_subtareas_nombre'), 'subtareas', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtareas_nombre'), table_name='subtareas')
    op.drop_index(op.f('ix_subtareas_id'), table_name='subtareas')
    op.drop_table('subtareas')
    # ### end Alembic commands ###
