"""Migración inicial

Revision ID: bc4fd043af44
Revises: 78b9d8b0f210
Create Date: 2024-11-19 21:10:21.179863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc4fd043af44'
down_revision: Union[str, None] = '78b9d8b0f210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtareas', 'dependencia_id',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtareas', 'dependencia_id',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    # ### end Alembic commands ###
